FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY --from=build /app/target/rss-bank-back.jar /app/rss-bank-back.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/rss-bank-back.jar"]
