name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build RSS-Bank-Eureka
        working-directory: ./RSS-Bank-Eureka
        run: mvn clean install -DskipTests

      - name: Run Tests for RSS-Bank-Eureka
        working-directory: ./RSS-Bank-Eureka
        run: mvn test

      - name: Build RSS-Bank-ConfigServer
        working-directory: ./RSS-Bank-ConfigServer
        run: mvn clean install -DskipTests

      - name: Run Tests for RSS-Bank-ConfigServer
        working-directory: ./RSS-Bank-ConfigServer
        run: mvn test

      - name: Build RSS-Bank-Gateway
        working-directory: ./RSS-Bank-Gateway
        run: mvn clean install -DskipTests

      - name: Run Tests for RSS-Bank-Gateway
        working-directory: ./RSS-Bank-Gateway
        run: mvn test

      - name: Build RSS-Bank-Back
        working-directory: ./RSS-Bank-Back
        run: mvn clean install -DskipTests

      - name: Run Tests for RSS-Bank-Back
        working-directory: ./RSS-Bank-Back
        run: mvn test

      - name: Build RSS-Bank-Auditoria
        working-directory: ./RSS-Bank-Auditoria
        run: mvn clean install -DskipTests

      - name: Run Tests for RSS-Bank-Auditoria
        working-directory: ./RSS-Bank-Auditoria
        run: mvn test

      - name: Upload JARs as artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            ./RSS-Bank-Eureka/target/*.jar
            ./RSS-Bank-ConfigServer/target/*.jar
            ./RSS-Bank-Gateway/target/*.jar
            ./RSS-Bank-Back/target/*.jar
            ./RSS-Bank-Auditoria/target/*.jar
